const projects = [
  {
    name: "Microsoft Club",
    imageUrl: "./images/microsoft.png",
    link: `https://microsoftissatso.vercel.app`,
    keywords: ["Next 13", "SSG", "SEO"],
  },
  {
    name: "Hestai",
    imageUrl: "./images/hestai.png",
    link: `https://www.hestai.ch`,
    keywords: ["Next 13", "Chatbot"],
  },
  {
    name: "Shoppi",
    imageUrl: "./images/shoppi.png",
    link: `https://shoppi.jacerchetoui.co`,
    keywords: [
      "Context API",
      "react-router",
      "Nodejs",
      "express",
      "mongoDB",
      "Authentication",
      "axios",
      "stripe",
    ],
  },
  {
    name: "Radio ESSTSS",
    imageUrl: "./images/esstss.png",
    link: `https://esstss-radio-23.vercel.app`,
    keywords: [
      "SSR",
      "SSG",
      "Node JS",
      "mongoDB",
      "Authentication",
      "OAuth",
      "axios",
    ],
  },
  {
    name: "Memory Game",
    imageUrl: "./images/memory-game.jpg",
    link: `https://memory-game.jacerchetoui.co`,
    keywords: [
      "useState",
      "useEffect",
      "localStorage",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "ToDo App",
    imageUrl: "./images/todo.jpg",
    link: `https://todoapp.jacerchetoui.co`,
    keywords: [
      "useState",
      "useEffect",
      "useRef",
      "form",
      "localStorage",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "Tenzies Game",
    imageUrl: "./images/tenzies-game.jpg",
    link: `https://tenzies-game.jacerchetoui.co`,
    keywords: ["useState", "useEffect", "Events", "conditional rendering"],
  },
  {
    name: "GitFinder",
    imageUrl: "./images/gitfinder.jpg",
    link: `https://githubfinder.jacerchetoui.co`,
    keywords: ["tailwindCSS", "useState", "useEffect", "Events", "Fetch API"],
  },
  {
    name: "Quizzical",
    imageUrl: "./images/quizzical.jpg",
    link: `https://quizzical.jacerchetoui.co`,
    keywords: [
      "useState",
      "useEffect",
      "useMemo",
      "Events",
      "conditional rendering",
      "fetch API",
    ],
  },
  {
    name: "Shopping Cart",
    imageUrl: "./images/cart.jpg",
    link: `https://comfy-griffin-4b2cda.netlify.app/`,
    keywords: [
      "SCSS",
      "useReducer",
      "useContext",
      "useState",
      "useEffect",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "Stripe Submenu",
    imageUrl: "./images/stripe.jpg",
    link: `https://main--sprightly-stardust-3cf41a.netlify.app/`,
    keywords: [
      "useContext",
      "useRef",
      "useState",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "SideBar",
    imageUrl: "./images/sidebar.jpg",
    link: `https://rad-semifreddo-e7157d.netlify.app/`,
    keywords: [
      "useContext",
      "custom Hooks",
      "useState",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "Meme Generator",
    imageUrl: "./images/memegenerator.jpg",
    link: `https://main--super-madeleine-82b53f.netlify.app/`,
    keywords: [
      "useState",
      "useEffect",
      "form",
      "Events",
      "conditional rendering",
      "fetch API",
    ],
  },
  {
    name: "Slider",
    imageUrl: "./images/slider.jpg",
    link: `https://62bf12c052fa9e0366d72abd--voluble-malabi-8bdfdd.netlify.app/`,
    keywords: ["useState", "useEffect", "Events", "conditional rendering"],
  },
  {
    name: "Tours",
    imageUrl: "./images/tours.jpg",
    link: `https://tours.jacerchetoui.co`,
    keywords: [
      "useState",
      "useEffect",
      "fetch API",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "Color Generator",
    imageUrl: "./images/color-generator.jpg",
    link: `https://colorgenerator.jacerchetoui.co`,
    keywords: [
      "form",
      "useState",
      "useEffect",
      "fetch API",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "Reviews",
    imageUrl: "./images/reviews.jpg",
    link: `https://reviews.jacerchetoui.co`,
    keywords: ["useState", "Events"],
  },
  {
    name: "navbar",
    imageUrl: "./images/navbar.jpg",
    link: `https://navbar.jacerchetoui.co`,
    keywords: [
      "useState",
      "useEffect",
      "useRef",
      "Events",
      "conditional rendering",
    ],
  },
  {
    name: "Food Menu",
    imageUrl: "./images/food-menu.jpg",
    link: `https://illustrious-pony-6d8a85.netlify.app/`,
    keywords: ["useState", "Events", "conditional rendering"],
  },
  {
    name: "Lorem Generator",
    imageUrl: "./images/lorem-generator.jpg",
    link: `https://main--frolicking-panda-6dcec3.netlify.app/`,
    keywords: ["useState", "conditional rendering", "form"],
  },
];

export default projects;
